name: Publish Docker base images

on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [18, 20, 22]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Publish thumbsup/runtime
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: ./docker/Dockerfile.runtime
          build-args: NODE_VERSION=${{ matrix.nodejs }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/thumbsup/runtime:node-${{ matrix.nodejs }}
          push: true
      - name: Publish thumbsup/build
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: ./docker/Dockerfile.build
          build-args: NODE_VERSION=${{ matrix.nodejs }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/thumbsup/build:node-${{ matrix.nodejs }}
          push: true
